---
--- Generated by Code，请勿修改
--- Created by liuxiuyang.
--- DateTime: 2026/08/03 17:19
--- ResPath: UIRes/Prefabs/Assets/GameResources/Prefabs/UIRes/Login/UILogin.prefab
--- ClassName: UI.Login.UILogin
---

local UIBaseLogic = require("Framework.UI.UIBaseLogic")
-------------------------------Object Binder Generated（请勿修改）-------------------------------
---@class UILogin.Widget
---@field root UnityEngine.RectTransform
---@field btn_login UnityEngine.UI.Button

--------------------------------Logic Bind Generated（请勿修改）---------------------------------
---@class UILogin.Logic
-----------------------------------Object Binder Generated End----------------------------------

---@class UILoginAuto : UIBaseLogic
---@field Widget UILogin.Widget
---@field Logic UILogin.Logic
local UILogin = DefineClass("UILogin", UIBaseLogic)

----- 自动绑定 -----
function UILogin:BindAll()
    self.Widget.btn_login.onClick:AddListener(Func(self, self.onClick_btn_login))
end

----- 生成的绑定函数 -----
function UILogin:onClick_btn_login() end


----- 清空绑定 -----
function UILogin:ReleaseBind()
    if self.Widget.btn_login then self.Widget.btn_login.onClick:RemoveAllListeners() end
end

----- 状态组 -----


return UILogin
