---
--- Generated by Code，请勿修改
--- Created by liuxiuyang.
--- DateTime: 2026/08/03 17:32
--- ResPath: UIRes/Prefabs/Assets/GameResources/Prefabs/UIRes/Login/UITest.prefab
--- ClassName: UI.Login.UITest
---

local UIBaseLogic = require("Framework.UI.UIBaseLogic")
-------------------------------Object Binder Generated（请勿修改）-------------------------------
---@class UITest.Widget
---@field root UnityEngine.RectTransform

--------------------------------Logic Bind Generated（请勿修改）---------------------------------
---@class UITest.Logic
-----------------------------------Object Binder Generated End----------------------------------

---@class UITestAuto : UIBaseLogic
---@field Widget UITest.Widget
---@field Logic UITest.Logic
local UITest = DefineClass("UITest", UIBaseLogic)

----- 自动绑定 -----
function UITest:BindAll()
    
end

----- 生成的绑定函数 -----


----- 清空绑定 -----
function UITest:ReleaseBind()
    
end

----- 状态组 -----


return UITest
