---
--- Generated by Code，请勿修改
--- Created by liuxiuyang.
--- DateTime: 2026/08/05 09:45
--- ResPath: UIRes/Prefabs/Assets/GameResources/Prefabs/UIRes/Main/UIMainView.prefab
--- ClassName: UI.Main.UIMainView
---

local UIBaseLogic = require("Framework.UI.UIBaseLogic")
-------------------------------Object Binder Generated（请勿修改）-------------------------------
---@class UIMainView.Widget
---@field root UnityEngine.RectTransform
---@field txt_test TMPro.TextMeshProUGUI

--------------------------------Logic Bind Generated（请勿修改）---------------------------------
---@class UIMainView.Logic
-----------------------------------Object Binder Generated End----------------------------------

---@class UIMainViewAuto : UIBaseLogic
---@field Widget UIMainView.Widget
---@field Logic UIMainView.Logic
local UIMainView = DefineClass("UIMainView", UIBaseLogic)

----- 自动绑定 -----
function UIMainView:BindAll()
    
end

----- 生成的绑定函数 -----


----- 清空绑定 -----
function UIMainView:ReleaseBind()
    
end

----- 状态组 -----


return UIMainView
