using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Game.Battle.TurnBased.Authoring;
using Game.Battle.TurnBased.RuntimeData;
using UnityEditor;
using UnityEngine;

namespace Game.Battle.Editor
{
    internal static class TurnBasedLogicDataAuthoringUtility
    {
        private const string GeneratedRoot =
            "Packages/LxyGame/LxyGame.Logic/Runtime/Battle/TurnBased/Generated";

        public static void GenerateAll()
        {
            List<TurnBasedSkillLogicAsset> assets =
                TurnBasedAssetEditorUtility.FindAssets<TurnBasedSkillLogicAsset>();
            for (int index = 0; index < assets.Count; index++)
            {
                if (!assets[index].TryValidate(out string error))
                {
                    throw new InvalidOperationException(
                        $"技能逻辑 {assets[index].LogicId} 校验失败：{error}");
                }
            }

            for (int index = 0; index < assets.Count; index++)
            {
                GenerateCode(assets[index]);
            }
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
            Debug.Log($"[TurnBasedLogicEditor] 已生成 {assets.Count} 份技能逻辑 C#。");
        }

        public static void ShowTemplateMenu(
            TurnBasedSkillLogicAsset asset,
            Action changed)
        {
            if (asset == null)
            {
                return;
            }

            var menu = new GenericMenu();
            AddTemplateMenuItem(menu, "主动伤害技能", asset, ActiveDamageTemplate, changed);
            AddTemplateMenuItem(menu, "被动触发与计数", asset, PassiveTemplate, changed);
            AddTemplateMenuItem(
                menu,
                "Buff / 召唤参数（召唤预留）",
                asset,
                BuffSummonTemplate,
                changed);
            menu.ShowAsContext();
        }

        public static string GenerateCode(TurnBasedSkillLogicAsset asset)
        {
            if (asset == null)
            {
                throw new ArgumentNullException(nameof(asset));
            }
            if (!asset.TryValidate(out string error))
            {
                throw new InvalidOperationException(error);
            }

            string suffix = StableHash(asset.LogicId).ToString("X8", CultureInfo.InvariantCulture);
            string identifier = ToPascalIdentifier(asset.LogicId);
            string className = $"SkillLogicData_{identifier}_{suffix}";
            string relativePath = $"{GeneratedRoot}/{className}.Data.g.cs";
            string projectRoot = Directory.GetParent(Application.dataPath)?.FullName ??
                throw new InvalidOperationException("无法定位 Unity 工程目录。");
            string absolutePath = Path.Combine(
                projectRoot,
                relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath) ?? projectRoot);
            File.WriteAllText(absolutePath, BuildSource(asset, className), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(relativePath, ImportAssetOptions.ForceUpdate);
            return relativePath;
        }

        internal static string BuildSource(
            TurnBasedSkillLogicAsset asset,
            string className)
        {
            var builder = new StringBuilder(4096);
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// 由技能逻辑编辑器生成。请修改对应 ScriptableObject 后重新生成。");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("using Game.Battle.TurnBased.Domain;");
            builder.AppendLine("using Game.Battle.TurnBased.RuntimeData;");
            builder.AppendLine();
            builder.AppendLine("namespace Game.Battle.TurnBased.Generated");
            builder.AppendLine("{");
            builder.Append("    public static class ").Append(className).AppendLine();
            builder.AppendLine("    {");
            builder.Append("        public const string LogicId = \"")
                .Append(Escape(asset.LogicId)).AppendLine("\";");
            builder.AppendLine();
            builder.AppendLine("        public static class Data");
            builder.AppendLine("        {");

            var data = new List<BattleLogicDataAuthoring>(asset.DataDefinitions.Count);
            for (int index = 0; index < asset.DataDefinitions.Count; index++)
            {
                data.Add(asset.DataDefinitions[index]);
            }
            data.Sort((left, right) => left.key.CompareTo(right.key));
            for (int index = 0; index < data.Count; index++)
            {
                BattleLogicDataAuthoring item = data[index];
                string name = ToPascalIdentifier(item.name) + "_" + item.key;
                builder.Append("            public const int ").Append(name)
                    .Append("Key = ").Append(item.key).AppendLine(";");
                if (item.valueType == BattleLogicDataValueType.BasisPoint)
                    builder.Append("            // 配置百分比：")
                        .Append(item.defaultValue.ToString("R", CultureInfo.InvariantCulture))
                        .AppendLine("%；以下值为编译后的定点比例 Raw，仅供运行时使用。");
                builder.Append("            public const long ").Append(name)
                    .Append("Default = ").Append(BattlePercentageAuthoring.Encode(
                        item.defaultValue, item.valueType == BattleLogicDataValueType.BasisPoint))
                    .AppendLine("L;");
            }
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        public static class Rules");
            builder.AppendLine("        {");
            IReadOnlyList<BattleRuleAuthoring> rules = asset.Rules;
            var orderedRules = new List<BattleRuleAuthoring>(rules.Count);
            for (int index = 0; index < rules.Count; index++)
            {
                orderedRules.Add(rules[index]);
            }
            orderedRules.Sort((left, right) => left.id.CompareTo(right.id));
            for (int index = 0; index < orderedRules.Count; index++)
            {
                BattleRuleAuthoring rule = orderedRules[index];
                string ruleName = ToPascalIdentifier(rule.operationName);
                builder.Append("            public const int ").Append(ruleName)
                    .Append("_").Append(rule.id).Append(" = ")
                    .Append(rule.id).AppendLine(";");
            }
            builder.AppendLine("        }");
            AppendCompiledDataFactory(builder, data);
            var compiledRules = new List<CompiledRule>(asset.Compile());
            compiledRules.Sort((left, right) => left.Id.CompareTo(right.Id));
            AppendCompiledRuleFactory(builder, compiledRules);
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendCompiledDataFactory(
            StringBuilder builder,
            IReadOnlyList<BattleLogicDataAuthoring> data)
        {
            builder.AppendLine();
            builder.AppendLine("        public static CompiledBattleLogicData[] CreateDataDefinitions()");
            builder.AppendLine("        {");
            if (data.Count == 0)
            {
                builder.AppendLine("            return System.Array.Empty<CompiledBattleLogicData>();");
                builder.AppendLine("        }");
                return;
            }
            builder.AppendLine("            return new[]");
            builder.AppendLine("            {");
            for (int index = 0; index < data.Count; index++)
            {
                BattleLogicDataAuthoring item = data[index];
                BattleLogicVariableScope scope = item.kind == BattleLogicDataKind.Parameter
                    ? BattleLogicVariableScope.Invocation
                    : item.scope;
                builder.Append("                new CompiledBattleLogicData(new BattleVariableKey(")
                    .Append(item.key).Append("), \"").Append(Escape(item.name))
                    .Append("\", BattleLogicDataKind.").Append(item.kind)
                    .Append(", BattleLogicDataValueType.").Append(item.valueType)
                    .Append(", BattleLogicVariableScope.").Append(scope)
                    .Append(", ").Append(BattlePercentageAuthoring.Encode(item.defaultValue, item.valueType == BattleLogicDataValueType.BasisPoint)).AppendLine("L),");
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
        }

        private static void AppendCompiledRuleFactory(
            StringBuilder builder,
            IReadOnlyList<CompiledRule> rules)
        {
            builder.AppendLine();
            builder.AppendLine("        public static CompiledRule[] CreateRules()");
            builder.AppendLine("        {");
            builder.AppendLine("            return new[]");
            builder.AppendLine("            {");
            for (int ruleIndex = 0; ruleIndex < rules.Count; ruleIndex++)
            {
                CompiledRule rule = rules[ruleIndex];
                builder.AppendLine("                new CompiledRule(");
                builder.Append("                    new RuleId(").Append(rule.Id.Value).AppendLine("),");
                builder.Append("                    BattleEventType.").Append(rule.Trigger).AppendLine(",");
                builder.Append("                    BattleEventPhase.").Append(rule.Phase).AppendLine(",");
                builder.Append("                    ").Append(rule.Priority).AppendLine(",");
                AppendConditions(builder, rule.Conditions, 20);
                builder.AppendLine(",");
                AppendActions(builder, rule.Actions, 20);
                builder.AppendLine(",");
                builder.Append("                    ").Append(Bool(rule.OwnerMustBeAlive))
                    .AppendLine("),");
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
        }

        private static void AppendConditions(
            StringBuilder builder,
            IReadOnlyList<CompiledCondition> conditions,
            int indent)
        {
            string pad = new string(' ', indent);
            if (conditions == null || conditions.Count == 0)
            {
                builder.Append(pad).Append("System.Array.Empty<CompiledCondition>()");
                return;
            }
            builder.Append(pad).AppendLine("new[]");
            builder.Append(pad).AppendLine("{");
            for (int index = 0; index < (conditions?.Count ?? 0); index++)
            {
                CompiledCondition condition = conditions[index];
                builder.Append(pad).Append("    new CompiledCondition(")
                    .Append("CompiledConditionType.").Append(condition.Type).Append(", ");
                AppendTarget(builder, condition.Target);
                builder.Append(", ComparisonOperator.").Append(condition.Comparison)
                    .Append(", ").Append(condition.Value).Append("L, AttributeType.")
                    .Append(condition.Attribute).Append(", ").Append(condition.ReferenceId)
                    .Append(", ").Append(Bool(condition.Negate)).Append(", ");
                AppendValue(builder, condition.LeftValue);
                builder.Append(", ");
                AppendValue(builder, condition.RightValue);
                builder.AppendLine("),");
            }
            builder.Append(pad).Append("}");
        }

        private static void AppendActions(
            StringBuilder builder,
            IReadOnlyList<CompiledAction> actions,
            int indent)
        {
            string pad = new string(' ', indent);
            builder.Append(pad).AppendLine("new[]");
            builder.Append(pad).AppendLine("{");
            for (int index = 0; index < (actions?.Count ?? 0); index++)
            {
                CompiledAction action = actions[index];
                builder.Append(pad).Append("    new CompiledAction(CompiledActionType.")
                    .Append(action.Type).Append(", ");
                AppendTarget(builder, action.Target);
                builder.Append(", ");
                AppendValue(builder, action.Value);
                builder.Append(", AttributeType.").Append(action.Attribute)
                    .Append(", ").Append(action.ReferenceId)
                    .Append(", (CompiledActionFlags)").Append((int)action.Flags)
                    .Append(", ").Append(Bool(action.UseReferenceValue)).Append(", ");
                AppendValue(builder, action.ReferenceValue);
                builder.AppendLine("),");
            }
            builder.Append(pad).Append("}");
        }

        private static void AppendTarget(
            StringBuilder builder,
            CompiledTargetSelector target)
        {
            CompiledTargetSelector safe = target;
            builder.Append("new CompiledTargetSelector(TargetSelectorType.")
                .Append(safe.Type).Append(", ").Append(safe.Count)
                .Append(", ").Append(Bool(safe.IncludeDead)).Append(", ")
                .Append(safe.ConfigIdFilter).Append(')');
        }

        private static void AppendValue(
            StringBuilder builder,
            CompiledValue value)
        {
            CompiledValue safe = value;
            builder.Append("new CompiledValue(ValueSourceType.").Append(safe.Source)
                .Append(", ").Append(safe.Constant).Append("L, AttributeType.")
                .Append(safe.Attribute).Append(", ").Append(safe.ReferenceId)
                .Append(", ").Append(safe.ScaleBasisPoint).Append(", ")
                .Append(safe.Offset).Append("L, ").Append(Bool(safe.HasMinimum))
                .Append(", ").Append(safe.Minimum).Append("L, ")
                .Append(Bool(safe.HasMaximum)).Append(", ")
                .Append(safe.Maximum).Append("L, ")
                .Append(Bool(safe.UseDynamicScale)).Append(", ValueSourceType.")
                .Append(safe.DynamicScaleSource).Append(", ").Append(safe.DynamicScaleConstant)
                .Append("L, AttributeType.").Append(safe.DynamicScaleAttribute)
                .Append(", ").Append(safe.DynamicScaleReferenceId).Append(')');
        }

        private static string Bool(bool value) => value ? "true" : "false";

        private static void AddTemplateMenuItem(
            GenericMenu menu,
            string label,
            TurnBasedSkillLogicAsset asset,
            IReadOnlyList<TemplateItem> template,
            Action changed)
        {
            menu.AddItem(new GUIContent(label), false, () =>
            {
                int added = ApplyTemplate(asset, template);
                if (added > 0)
                {
                    changed?.Invoke();
                }
                EditorUtility.DisplayDialog(
                    "逻辑数据模板",
                    added > 0
                        ? $"已补充 {added} 个数据定义；已有同名定义不会覆盖。"
                        : "模板中的数据定义已经存在，未做修改。",
                    "确定");
            });
        }

        private static int ApplyTemplate(
            TurnBasedSkillLogicAsset asset,
            IReadOnlyList<TemplateItem> template)
        {
            var names = new HashSet<string>(StringComparer.Ordinal);
            var keys = new HashSet<int>();
            for (int index = 0; index < asset.DataDefinitions.Count; index++)
            {
                BattleLogicDataAuthoring existing = asset.DataDefinitions[index];
                if (existing == null)
                {
                    continue;
                }
                names.Add(existing.name ?? string.Empty);
                keys.Add(existing.key);
            }

            Undo.RecordObject(asset, "应用战斗逻辑数据模板");
            int added = 0;
            for (int index = 0; index < template.Count; index++)
            {
                TemplateItem item = template[index];
                if (names.Contains(item.Name))
                {
                    continue;
                }

                int key = item.Key;
                while (keys.Contains(key) && key < int.MaxValue)
                {
                    key++;
                }
                if (key <= 0 || keys.Contains(key))
                {
                    throw new InvalidOperationException("无法为逻辑数据模板分配唯一 Key。");
                }

                asset.AddDataDefinition(new BattleLogicDataAuthoring
                {
                    name = item.Name,
                    key = key,
                    kind = item.Kind,
                    valueType = item.ValueType,
                    scope = item.Scope,
                    defaultValue = item.DefaultValue,
                    description = item.Description,
                });
                names.Add(item.Name);
                keys.Add(key);
                added++;
            }

            if (added > 0)
            {
                EditorUtility.SetDirty(asset);
            }
            return added;
        }

        private static string ToPascalIdentifier(string source)
        {
            string safe = source ?? string.Empty;
            var builder = new StringBuilder(safe.Length + 8);
            bool upper = true;
            for (int index = 0; index < safe.Length; index++)
            {
                char character = safe[index];
                if (!char.IsLetterOrDigit(character))
                {
                    upper = true;
                    continue;
                }

                if (builder.Length == 0 && char.IsDigit(character))
                {
                    builder.Append('N');
                }
                builder.Append(upper ? char.ToUpperInvariant(character) : character);
                upper = false;
            }
            return builder.Length == 0 ? "Unnamed" : builder.ToString();
        }

        private static string Escape(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static uint StableHash(string value)
        {
            const uint offset = 2166136261;
            const uint prime = 16777619;
            uint hash = offset;
            string safe = value ?? string.Empty;
            unchecked
            {
                for (int index = 0; index < safe.Length; index++)
                {
                    hash ^= safe[index];
                    hash *= prime;
                }
            }
            return hash;
        }

        private readonly struct TemplateItem
        {
            public TemplateItem(
                int key,
                string name,
                BattleLogicDataKind kind,
                BattleLogicDataValueType valueType,
                BattleLogicVariableScope scope,
                double defaultValue,
                string description)
            {
                Key = key;
                Name = name;
                Kind = kind;
                ValueType = valueType;
                Scope = scope;
                DefaultValue = defaultValue;
                Description = description;
            }

            public int Key { get; }
            public string Name { get; }
            public BattleLogicDataKind Kind { get; }
            public BattleLogicDataValueType ValueType { get; }
            public BattleLogicVariableScope Scope { get; }
            public double DefaultValue { get; }
            public string Description { get; }
        }

        private static readonly TemplateItem[] ActiveDamageTemplate =
        {
            new TemplateItem(1001, "damage_rate", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.BasisPoint, BattleLogicVariableScope.Invocation,
                100, "基础伤害倍率，100 表示 100%。"),
            new TemplateItem(1002, "trigger_chance", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.BasisPoint, BattleLogicVariableScope.Invocation,
                100, "触发概率，100 表示必定触发。"),
            new TemplateItem(2001, "cast_count", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Skill,
                0, "该单位的此技能在本场战斗累计释放次数。"),
            new TemplateItem(3001, "temp_value", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Invocation,
                0, "当前规则触发期间复用的中间计算值。"),
        };

        private static readonly TemplateItem[] PassiveTemplate =
        {
            new TemplateItem(1002, "trigger_chance", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.BasisPoint, BattleLogicVariableScope.Invocation,
                100, "被动触发概率，100 表示必定触发。"),
            new TemplateItem(2001, "trigger_count", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Skill,
                0, "本场战斗累计触发次数。"),
            new TemplateItem(2002, "last_trigger_round", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Skill,
                0, "最近一次成功触发的回合。"),
            new TemplateItem(3001, "temp_value", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Invocation,
                0, "当前规则触发期间的中间计算值。"),
        };

        private static readonly TemplateItem[] BuffSummonTemplate =
        {
            new TemplateItem(1101, "buff_id", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.Identifier, BattleLogicVariableScope.Invocation,
                0, "需要添加或移除的 Buff 配置 ID。"),
            new TemplateItem(1102, "buff_stack", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Invocation,
                1, "Buff 初始层数。"),
            new TemplateItem(1103, "summon_config_id", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.Identifier, BattleLogicVariableScope.Invocation,
                0, "召唤单位配置 ID。"),
            new TemplateItem(1104, "summon_count", BattleLogicDataKind.Parameter,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Invocation,
                1, "召唤数量。"),
            new TemplateItem(3002, "temp_target_count", BattleLogicDataKind.RuntimeVariable,
                BattleLogicDataValueType.Integer, BattleLogicVariableScope.Invocation,
                0, "当前触发中选中的目标数量。"),
        };
    }
}
