---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuxiuyang.
--- DateTime: 2026/8/3 16:34
---
require("Framework.Core.__Require")

Game = {}

Game.SceneMgr = require("Managers.Scene.SceneMgr")

---@type UIManager
Game.UIManager = require("Framework.UI.UIManager")
