org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=.bytes, .json, .version, .hash
unityTemplateVersion=7
android.useAndroidX=true
android.enableJetifier=true
org.gradle.welcome=never
android.aapt2FromMavenOverride=D\:\\UnityAndroid\\2022.3\\SDK\\build-tools\\34.0.0\\aapt2.exe